name = "app-worker"
main = "backend/build/worker/shim.mjs"
compatibility_date = "2026-02-23"
workers_dev = true

[build]
command = "cd backend && worker-build --release"

[vars]
APP_ENV = "production"
API_BASE_URL = "https://example.com"

[[d1_databases]]
binding = "DB"
database_name = "gf-db"
database_id = "4f310aad-b888-4ba0-84c2-22a6b8ca222f"
migrations_dir = "./backend/migrations"
